In [1]:
import pandas as pd
import numpy as np

In [2]:
sample_sub = pd.read_csv('sample_submission.csv')

In [3]:
sample_sub.head()

             date_time  traffic_volume
0  1969-05-17 21:00:00             500
1  1969-05-17 21:00:00             530
2  1969-05-17 21:00:00             545
3  1969-05-17 22:00:00             750

In [4]:
df = pd.read_csv('Train.csv')

In [5]:
df.head(10)

,date_time,is_holiday,air_pollution_index,humidity,wind_speed,wind_direction,visibility_in_miles,dew_point,temperature,rain_p_h,snow_p_h,clouds_all,weather_type,weather_description,traffic_volume
0,2012-10-02 09:00:00,None,121,89,2,329,1,1,288.28,0.0,0.0,40,Clouds,scattered clouds,5545
1,2012-10-02 10:00:00,None,178,67,3,330,1,1,289.36,0.0,0.0,75,Clouds,broken clouds,4516
2,2012-10-02 11:00:00,None,113,66,3,329,2,2,289.58,0.0,0.0,90,Clouds,overcast clouds,4767
3,2012-10-02 12:00:00,None,20,66,3,329,5,5,290.13,0.0,0.0,90,Clouds,overcast clouds,5026
4,2012-10-02 13:00:00,None,281,65,3,329,7,7,291.14,0.0,0.0,75,Clouds,broken clouds,4918
5,2012-10-02 14:00:00,None,23,65,3,328,6,6,291.72,0.0,0.0,1,Clear,sky is clear,5181
6,2012-10-02 15:00:00,None,184,64,3,328,7,7,293.17,0.0,0.0,1,Clear,sky is clear,5584
7,2012-10-02 16:00:00,None,167,64,3,327,7,7,293.86,0.0,0.0,1,Clear,sky is clear,6015
8,2012-10-02 17:00:00,None,119,63,3,327,6,6,294.14,0.0,0.0,20,Clouds,few clouds,5791
9,2012-10-02 18:00:00,None,161,63,3,326,3,3,293.10,0.0,0.0,20,Clouds,few clouds,4770

In [6]:
df.shape

(33750, 15)

In [7]:
df['weather_type'].unique()

array(['Clouds', 'Clear', 'Rain', 'Drizzle', 'Mist', 'Haze', 'Fog',
       'Thunderstorm', 'Snow', 'Squall', 'Smoke'], dtype=object)

In [8]:
df['clouds_all'].unique()

array([ 40,  75,  90,   1,  20,   0, 100,  92,  99,  81,  50,  72,  56,
        57,  93,  85,  68,  87,  91,  96,  48,  60,   8,  38,  46,  98,
        86,  16,   6,  59,  54,  89,  78,  36,  17,  58,  63,  42,  25,
        11,  13,  83,  70,  84,   3,  77,  88,  67,  97,  62,  32,   4,
         5,   2,  44,  24,  76,  64,  80,  12])

In [9]:
df['humidity'].unique()

array([ 89,  67,  66,  65,  64,  63,  62,  61,  60,  59,  58,  57,  56,
        55,  48,  42,  33,  30,  32,  37,  36,  39,  41,  44,  47,  50,
        75,  70,  93,  84,  53,  49,  45,  28,  26,  34,  54,  71,  76,
        35,  27,  25,  23,  24,  31,  52,  69,  80,  74,  38,  51,  79,
        21,  43,  68,  87,  86,  29,  40,  92,  19,  18,  20,  81, 100,
        46,  83,  85,  88,  90,  95,  97,  91,  78,  82,  72,  77,  73,
        94,  96,  98,  17,  22,  99,  15,  16,  14,  13])

In [10]:
df['wind_speed'].unique()

array([ 2,  3,  4,  5,  7,  6,  0,  1,  9,  8, 10, 12, 11, 13, 15, 14, 16])

In [11]:
df['year'] = pd.DatetimeIndex(df['date_time']).year

In [12]:
df['month'] = pd.DatetimeIndex(df['date_time']).month

In [ ]:
df.describe()

In [13]:
df['is_holiday'].unique()

array(['None', 'Columbus Day', 'Veterans Day', 'Thanksgiving Day',
       'Christmas Day', 'New Years Day', 'Washingtons Birthday',
       'Memorial Day', 'Independence Day', 'State Fair', 'Labor Day',
       'Martin Luther King Jr Day'], dtype=object)

In [18]:
mapping = {'None':0, 'Columbus Day':1, 'Veterans Day':2, 'Thanksgiving Day':3,
       'Christmas Day':4, 'New Years Day':5, 'Washingtons Birthday':6,
       'Memorial Day':7, 'Independence Day':8, 'State Fair':9, 'Labor Day':10,
       'Martin Luther King Jr Day':11}
x_train.replace({'is_holiday': mapping})

,is_holiday,air_pollution_index,humidity,wind_speed,wind_direction,visibility_in_miles,dew_point,temperature,rain_p_h,snow_p_h,clouds_all,weather_type,year,month
0,0,121,89,2,329,1,1,288.28,0.0,0.0,40,Clouds,2012,10
1,0,178,67,3,330,1,1,289.36,0.0,0.0,75,Clouds,2012,10
2,0,113,66,3,329,2,2,289.58,0.0,0.0,90,Clouds,2012,10
3,0,20,66,3,329,5,5,290.13,0.0,0.0,90,Clouds,2012,10
4,0,281,65,3,329,7,7,291.14,0.0,0.0,75,Clouds,2012,10
5,0,23,65,3,328,6,6,291.72,0.0,0.0,1,Clear,2012,10
6,0,184,64,3,328,7,7,293.17,0.0,0.0,1,Clear,2012,10
7,0,167,64,3,327,7,7,293.86,0.0,0.0,1,Clear,2012,10
8,0,119,63,3,327,6,6,294.14,0.0,0.0,20,Clouds,2012,10
9,0,161,63,3,326,3,3,293.10,0.0,0.0,20,Clouds,2012,10
10,0,243,62,3,326,8,8,290.97,0.0,0.0,20,Clouds,2012,10
11,0,150,62,3,326,5,5,289.38,0.0,0.0,1,Clear,2012,10
12,0,128,61,4,325,4,4,288.61,0.0,0.0,1,Clear,2012,10
13,0,18,61,4,325,7,7,287.16,0.0,0.0,1,Clear,2012,10
14,0,186,60,4,324,5,5,285.45,0.0,0.0,1,Clear,2012,10
15,0,58,60,4,324,2,2,284.63,0.0,0.0,1,Clear,2012,10
16,0,158,59,4,324,6,6,283.47,0.0,0.0,1,Clear,2012,10
17,0,166,59,4,323,1,1,281.18,0.0,0.0,1,Clear,2012,10
18,0,101,58,4,323,7,7,281.09,0.0,0.0,1,Clear,2012,10
19,0,161,58,4,322,4,4,279.53,0.0,0.0,1,Clear,2012,10
20,0,179,57,4,322,3,3,278.62,0.0,0.0,1,Clear,2012,10
21,0,93,57,4,322,4,4,278.23,0.0,0.0,1,Clear,2012,10
22,0,57,56,4,321,4,4,278.12,0.0,0.0,1,Clear,2012,10
23,0,226,56,4,321,4,4,282.48,0.0,0.0,1,Clear,2012,10
24,0,86,55,4,320,3,3,291.97,0.0,0.0,1,Clear,2012,10
25,0,52,55,4,320,1,1,293.23,0.0,0.0,1,Clear,2012,10
26,0,273,55,4,320,4,4,294.31,0.0,0.0,1,Clear,2012,10
27,0,72,55,5,350,3,3,295.17,0.0,0.0,1,Clear,2012,10
28,0,254,55,4,320,1,1,295.13,0.0,0.0,1,Clear,2012,10
29,0,129,55,5,330,4,4,293.66,0.0,0.0,20,Clouds,2012,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33720,0,284,85,2,315,7,7,290.22,0.0,0.0,90,Mist,2017,5
33721,0,32,85,2,315,6,6,290.22,0.0,0.0,90,Drizzle,2017,5
33722,0,75,72,2,340,8,8,291.02,0.0,0.0,90,Rain,2017,5
33723,0,95,72,2,340,9,9,291.75,0.0,0.0,90,Rain,2017,5
33724,0,209,73,1,180,6,6,291.75,0.0,0.0,90,Mist,2017,5
33725,0,96,68,1,315,6,6,292.09,0.0,0.0,90,Rain,2017,5
33726,0,236,68,3,341,1,1,292.09,0.0,0.0,90,Drizzle,2017,5
33727,0,120,68,3,341,1,1,292.62,0.0,0.0,90,Rain,2017,5
33728,0,148,62,2,335,7,7,293.15,0.0,0.0,40,Rain,2017,5
33729,0,244,62,1,318,5,5,292.75,0.0,0.0,90,Rain,2017,5
33730,0,271,62,1,333,6,6,292.75,0.0,0.0,90,Mist,2017,5
33731,0,218,59,2,334,6,6,292.09,0.0,0.0,90,Rain,2017,5
33732,0,237,62,2,334,4,4,292.09,0.0,0.0,90,Mist,2017,5
33733,0,194,69,2,334,2,2,291.35,0.0,0.0,90,Rain,2017,5
33734,0,91,67,2,337,8,8,291.35,0.0,0.0,90,Mist,2017,5
33735,0,170,67,2,337,4,4,291.35,0.0,0.0,90,Drizzle,2017,5
33736,0,198,67,2,337,2,2,291.35,0.0,0.0,90,Thunderstorm,2017,5
33737,0,27,84,1,321,4,4,290.56,0.0,0.0,90,Drizzle,2017,5
33738,0,16,84,1,321,8,8,290.56,0.0,0.0,90,Thunderstorm,2017,5
33739,0,294,84,1,321,3,3,290.56,0.0,0.0,90,Rain,2017,5
33740,0,206,86,1,326,5,5,288.89,0.0,0.0,90,Thunderstorm,2017,5
33741,0,232,86,1,326,6,6,288.89,0.0,0.0,90,Rain,2017,5
33742,0,83,86,1,326,1,1,288.89,0.0,0.0,90,Mist,2017,5
33743,0,25,85,1,328,8,8,287.88,0.0,0.0,90,Thunderstorm,2017,5
33744,0,269,85,1,328,5,5,287.88,0.0,0.0,90,Rain,2017,5
33745,0,74,85,1,328,7,7,287.88,0.0,0.0,90,Mist,2017,5
33746,0,81,70,1,24,2,2,286.95,0.0,0.0,90,Rain,2017,5
33747,0,138,70,1,24,1,1,286.95,0.0,0.0,90,Mist,2017,5
33748,0,229,66,1,42,6,6,285.75,0.0,0.0,90,Rain,2017,5
33749,0,140,63,1,27,8,8,285.75,0.0,0.0,90,Mist,2017,5

In [15]:
x_train = df
y_train = df['traffic_volume']

In [16]:
x_train = x_train.drop(['traffic_volume','weather_description','date_time'],axis=1)

In [17]:
x_train

,is_holiday,air_pollution_index,humidity,wind_speed,wind_direction,visibility_in_miles,dew_point,temperature,rain_p_h,snow_p_h,clouds_all,weather_type,year,month
0,None,121,89,2,329,1,1,288.28,0.0,0.0,40,Clouds,2012,10
1,None,178,67,3,330,1,1,289.36,0.0,0.0,75,Clouds,2012,10
2,None,113,66,3,329,2,2,289.58,0.0,0.0,90,Clouds,2012,10
3,None,20,66,3,329,5,5,290.13,0.0,0.0,90,Clouds,2012,10
4,None,281,65,3,329,7,7,291.14,0.0,0.0,75,Clouds,2012,10
5,None,23,65,3,328,6,6,291.72,0.0,0.0,1,Clear,2012,10
6,None,184,64,3,328,7,7,293.17,0.0,0.0,1,Clear,2012,10
7,None,167,64,3,327,7,7,293.86,0.0,0.0,1,Clear,2012,10
8,None,119,63,3,327,6,6,294.14,0.0,0.0,20,Clouds,2012,10
9,None,161,63,3,326,3,3,293.10,0.0,0.0,20,Clouds,2012,10
10,None,243,62,3,326,8,8,290.97,0.0,0.0,20,Clouds,2012,10
11,None,150,62,3,326,5,5,289.38,0.0,0.0,1,Clear,2012,10
12,None,128,61,4,325,4,4,288.61,0.0,0.0,1,Clear,2012,10
13,None,18,61,4,325,7,7,287.16,0.0,0.0,1,Clear,2012,10
14,None,186,60,4,324,5,5,285.45,0.0,0.0,1,Clear,2012,10
15,None,58,60,4,324,2,2,284.63,0.0,0.0,1,Clear,2012,10
16,None,158,59,4,324,6,6,283.47,0.0,0.0,1,Clear,2012,10
17,None,166,59,4,323,1,1,281.18,0.0,0.0,1,Clear,2012,10
18,None,101,58,4,323,7,7,281.09,0.0,0.0,1,Clear,2012,10
19,None,161,58,4,322,4,4,279.53,0.0,0.0,1,Clear,2012,10
20,None,179,57,4,322,3,3,278.62,0.0,0.0,1,Clear,2012,10
21,None,93,57,4,322,4,4,278.23,0.0,0.0,1,Clear,2012,10
22,None,57,56,4,321,4,4,278.12,0.0,0.0,1,Clear,2012,10
23,None,226,56,4,321,4,4,282.48,0.0,0.0,1,Clear,2012,10
24,None,86,55,4,320,3,3,291.97,0.0,0.0,1,Clear,2012,10
25,None,52,55,4,320,1,1,293.23,0.0,0.0,1,Clear,2012,10
26,None,273,55,4,320,4,4,294.31,0.0,0.0,1,Clear,2012,10
27,None,72,55,5,350,3,3,295.17,0.0,0.0,1,Clear,2012,10
28,None,254,55,4,320,1,1,295.13,0.0,0.0,1,Clear,2012,10
29,None,129,55,5,330,4,4,293.66,0.0,0.0,20,Clouds,2012,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33720,None,284,85,2,315,7,7,290.22,0.0,0.0,90,Mist,2017,5
33721,None,32,85,2,315,6,6,290.22,0.0,0.0,90,Drizzle,2017,5
33722,None,75,72,2,340,8,8,291.02,0.0,0.0,90,Rain,2017,5
33723,None,95,72,2,340,9,9,291.75,0.0,0.0,90,Rain,2017,5
33724,None,209,73,1,180,6,6,291.75,0.0,0.0,90,Mist,2017,5
33725,None,96,68,1,315,6,6,292.09,0.0,0.0,90,Rain,2017,5
33726,None,236,68,3,341,1,1,292.09,0.0,0.0,90,Drizzle,2017,5
33727,None,120,68,3,341,1,1,292.62,0.0,0.0,90,Rain,2017,5
33728,None,148,62,2,335,7,7,293.15,0.0,0.0,40,Rain,2017,5
33729,None,244,62,1,318,5,5,292.75,0.0,0.0,90,Rain,2017,5
33730,None,271,62,1,333,6,6,292.75,0.0,0.0,90,Mist,2017,5
33731,None,218,59,2,334,6,6,292.09,0.0,0.0,90,Rain,2017,5
33732,None,237,62,2,334,4,4,292.09,0.0,0.0,90,Mist,2017,5
33733,None,194,69,2,334,2,2,291.35,0.0,0.0,90,Rain,2017,5
33734,None,91,67,2,337,8,8,291.35,0.0,0.0,90,Mist,2017,5
33735,None,170,67,2,337,4,4,291.35,0.0,0.0,90,Drizzle,2017,5
33736,None,198,67,2,337,2,2,291.35,0.0,0.0,90,Thunderstorm,2017,5
33737,None,27,84,1,321,4,4,290.56,0.0,0.0,90,Drizzle,2017,5
33738,None,16,84,1,321,8,8,290.56,0.0,0.0,90,Thunderstorm,2017,5
33739,None,294,84,1,321,3,3,290.56,0.0,0.0,90,Rain,2017,5
33740,None,206,86,1,326,5,5,288.89,0.0,0.0,90,Thunderstorm,2017,5
33741,None,232,86,1,326,6,6,288.89,0.0,0.0,90,Rain,2017,5
33742,None,83,86,1,326,1,1,288.89,0.0,0.0,90,Mist,2017,5
33743,None,25,85,1,328,8,8,287.88,0.0,0.0,90,Thunderstorm,2017,5
33744,None,269,85,1,328,5,5,287.88,0.0,0.0,90,Rain,2017,5
33745,None,74,85,1,328,7,7,287.88,0.0,0.0,90,Mist,2017,5
33746,None,81,70,1,24,2,2,286.95,0.0,0.0,90,Rain,2017,5
33747,None,138,70,1,24,1,1,286.95,0.0,0.0,90,Mist,2017,5
33748,None,229,66,1,42,6,6,285.75,0.0,0.0,90,Rain,2017,5
33749,None,140,63,1,27,8,8,285.75,0.0,0.0,90,Mist,2017,5

# Training using Linear Regression

In [ ]:
from sklearn.ensemble import RandomForestRegressor

In [ ]:
model = RandomForestRegressor()

In [ ]:
model.fit(x_train, y_train)

In [ ]:
model.score(x_train, y_train)

In [ ]:
x_test = pd.read_csv('Test.csv')

In [ ]:
x_test = x_test.drop(['is_holiday', 'weather_type', 'weather_description','date_time'],axis=1)

In [ ]:
x_test

In [ ]:
output = model.predict(x_test)

In [ ]:
import requests

In [ ]:
payload = {'key1': 'value1', 'key2': 'value2'}

r = requests.post("https://httpbin.org/post", data=payload)
print(r.text)